### ISSUE TITLE
"LINK : fatal error LNK1181" when compiling with bootil

### ISSUE THREAD

**Issue by Minabsapi** [garrynewman/bootil#25]
Hello,
I used bootil to compile gmad as stated [here](https://github.com/garrynewman/gmad/blob/master/README.md)
However, I got a problem when compiling gmad.sln with msbuild:
 ```
LINK : fatal error LNK1181: unable to read input file 'bootil_
static.lib' [C:\Users\User\dir\gmad-master-new\GMad
.vcxproj]
```
I looked in the bootil directory and cannot find such file. Is it missing, or did I specified something I should have not ?

**Comment by robotboy655** [comment]
Please read the instructions in the readme of the gmad repository.

**Comment by Minabsapi** [comment]
Read and tried the new command. Didn't fix a thing...

**Comment by Minabsapi** [comment]
Finally noticed the files in "projects" and I tried to compile them with premake5, but I got an error
`Error: invalid value 'SEH' for flags`

**Comment by Minabsapi** [comment]
Thought I fixed by removing the SEH flag from the Lua files, but when doing the gmad compilation I got tons of errors. I'm out of ideas now...

**Comment by robotboy655** [comment]
Pushed a fix to the script, should work now.

**Comment by Minabsapi** [comment]
The compilation of the lib worked (despite a little 83 warnings)
However, same thing than with my "workaround": a ton of errors due to discordance. Not sure I understood what's wrong...

**Comment by Minabsapi** [comment]
Just a summary of what I did to see if there's something wrong:
1. `premake5 vs2015` in \bootil\projects
2. Compiled the obtained files with MSBuild with this basic command: `SET VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140& C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe Bootil.sln /p:Configuration=Release`
3. Put the obtained `bootil_static.lib` in \bootil\lib\windows\vs2015
4. `premake5 --outdir="bin/" --bootil_lib="bootil/lib/windows/vs2015/" --bootil_inc="bootil/include/" vs2015` in gmad-master (which contain the bootil directory we were earlier)
5. Compiled the obtained files the same way as previously, but with GMad.sln as target.

...Get 63 errors because of some value that were 2 instead of 0

**Comment by robotboy655** [comment]
Are you compiling both with the same toolset? I have built both with v141 toolset using vs2017 and it worked just fine.

**Comment by Minabsapi** [comment]
Yes I did. All with v140 since it's the only version I have.

**Comment by Minabsapi** [comment]
I would like to test out if it works for me with VS2017. Could you please send me the link the the 2017 (v141) build tools ? I can't find it anywhere

**Comment by Minabsapi** [comment]
Managed to download it and recompiled everything with the new toolset, but I still have the same issue (it's now just 58 errors, but still for the same reason). I am really confused...

**Comment by Minabsapi** [comment]
Here are samples of errors I get (translated):
``
bootil_static.lib(Buffer.obj) : error LNK2038: discordance found for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in create_gmad.obj [...\GMad.vcxproj]
`` 
``
bootil_static.lib(Tree.obj) : error LNK2001: unresolved external symbol __CrtDbgReport [...\GMad.vcxproj]
``

**Comment by ravo10** [comment]
I got the same 58 errors... I am using VS 2017:

- Windows 10 SDK (10.0.17763.0)

- VC++ 2017 version 15.9 v14.16 latest v141 tools

Maybe the instructions are a little unclear [here](https://github.com/Facepunch/gmad) for beginners? I made the `bootil_static.lib` the same way as Minabsapi. I used a .bat file with `premake5 vscode2017` for Bootil and a .bat with `premake4 vscode2017` for GMad..

The error codes (several of the same). This is from VS 2019; but I get the same with VS 2017. Maybe it is something with bootil_static.lib:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in create_gmad.obj	GMad	C:\Users\rarua\OneDrive\Documents\GMADD\gmad\bootil_static.lib(String_To.obj)	1
	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in create_gmad.obj	GMad	C:\Users\rarua\OneDrive\Documents\GMADD\gmad\bootil_static.lib(String_To.obj)	1
	
Error	LNK2001	unresolved external symbol __CrtDbgReport	GMad	C:\Users\rarua\OneDrive\Documents\GMADD\gmad\bootil_static.lib(String_To.obj)	1
	
Error	LNK2019	unresolved external symbol __free_dbg referenced in function "private: void __thiscall std::_Yarn<char>::_Tidy(void)" (?_Tidy@?$_Yarn@D@std@@AAEXXZ)	GMad	C:\Users\rarua\OneDrive\Documents\GMADD\gmad\bootil_static.lib(File.obj)	1
	
Error	LNK2019	unresolved external symbol __malloc_dbg referenced in function "public: static void * __cdecl std::_Crt_new_delete::operator new(unsigned int,struct std::nothrow_t const &)" (??2_Crt_new_delete@std@@SAPAXIABUnothrow_t@1@@Z)	GMad	C:\Users\rarua\OneDrive\Documents\GMADD\gmad\bootil_static.lib(File.obj)	1
	
Error	LNK1120	3 unresolved externals	GMad	C:\Users\rarua\OneDrive\Documents\GMADD\gmad\bin\gmad.exe	1
```

**Comment by ravo10** [comment]
OK, so after adjusting the compilation settings for the bootil project, it compiled GMad.exe succesfully. I used VS 2019.

**Here is what I changed. Go to: _Project => bootil_static Properties..._**

- C/C++ => Preprocessor => Preprocessor Definitions. Add: _ITERATOR_DEBUG_LEVEL=0
- C/C++ => Code Generation => Runtime Library. Choose: Multi-threaded (/MT)
